### ISSUE TITLE
Create sign up form with SSO (front end)

### ISSUE THREAD

**Issue by dopecello** [dopecello/music-jobs#1]
![image](https://user-images.githubusercontent.com/105554094/215217888-6ac7d5f2-3257-47ff-a38d-d46bc7601a15.png)

- Make it look similar but keep the same style as before like color scheme, etc.

DONT INCLUDE:
Login without password

**Comment by brian-gee** [comment]
Basic template is complete, having an issue getting correct spacing for text on icon buttons.

**Comment by dopecello** [comment]
I took the component you wrote and essentially copy-pasted with a few tweaks to the `className`'s. I deleted the `signUp.tsx` file as right now it isn't currently necessary. We can convert the TSX in the `access.tsx` file to a component later down the road if we want to include this template in other pages. Thanks for getting the bulk of that done:)
