### ISSUE TITLE
Create login button for top field of login

### ISSUE THREAD

**Issue by dopecello** [dopecello/music-jobs#13]
Just add a Login button that acts the same as the "About" button in the Nav but with a rounded border

![image](https://user-images.githubusercontent.com/105554094/216383669-c2b6205b-8fd5-43a4-ad41-adccdcb9ed07.png)

Be sure to assign the correct custom css class `buttons buttons:hover` so that it does the animation 

Insert here:
![image](https://user-images.githubusercontent.com/105554094/216383966-9c078214-b86d-4c2d-ac29-2e2182b20de0.png)

**Comment by Frenzoid** [comment]
Solved here: https://github.com/dopecello/music-jobs/pull/17
