### ISSUE TITLE
Facebook OAuth

### ISSUE THREAD

**Issue by dopecello** [dopecello/music-jobs#8]
If someone wants to try to tackle Facebook OAuth, that would be epic.

If anyone needs certain access to things in order to set it up just text me

Text any resources or thoughts here

++++++

it is done when I can sign up with my facebook account and firebase picks up my unique user information and stores it

it is done if when i try to repeat the process, that firestore does not duplicate my user info.

**Comment by brian-gee** [comment]
Pull request submitted. Need someone to test with their Facebook account to verify functionality.

**Comment by dopecello** [comment]
![image](https://user-images.githubusercontent.com/105554094/216369916-78599944-54d9-4416-ad8c-b576356268c5.png)

**Comment by dopecello** [comment]
I was working on it too and got it to work. set it up in firebase. Thank you. Will merge the favicon and header component you made now
